# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/vg00-root";
      fsType = "xfs";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/vg00-home";
      fsType = "xfs";
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/vg00-nix";
      fsType = "xfs";
    };

  fileSystems."/var" =
    { device = "/dev/mapper/vg00-var";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/38F1-9174";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/vg00-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
